package me.wcy.serviceloader.compiler

object ProcessorUtils {
    const val PARAM_MAP_NAME = "map"
    const val METHOD_LOAD_NAME = "load"
    const val PACKAGE_NAME = "me.wcy.serviceloader.apt"
    const val JAVADOC = "DO NOT EDIT THIS FILE! IT WAS GENERATED BY SERVICE LOADER.\n"

    fun formatModuleName(moduleName: String): String {
        return moduleName.replace('-', '_')
    }

    fun formatArray(array: Array<String>): String {
        val sb = StringBuilder()
        array.forEach {
            sb.append("\"$it\"").append(",")
        }
        if (sb.isNotEmpty()) {
            sb.deleteAt(sb.length - 1)
        }
        return "arrayOf($sb)"
    }
}